### ISSUE TITLE
Remove the V global nickname

### ISSUE THREAD

**Issue by phoe** [Shinmera/verbose#5]
https://github.com/Shinmera/verbose/blob/c5b7ecd465be61b35af17ef57564697b88397174/package.lisp#L10

With the omnipresence of package-local nicknames, very short global nicknames become unnecessary - hence I propose removing the `v` nickname from Verbose.

The obvious cost of doing this is breaking backwards compatibility: all code that uses the `v` nickname will fail to compile after the change. The affected packages will need to have the `(:local-nicknames (#:v #:verbose))` option added to their definitions.

Is it feasible? Has the impact of doing so been anyhow measured? How much Quicklisp code depends on this nickname?

**Comment by Shinmera** [comment]
There is stuff in QL that depends on the nickname, I know that much for sure. Code that's not on QL and isn't mine that does, exists too.

I've been meaning to make this change for a while though, so it's definitely coming, just not sure when. Might come with a general breaking change to all my systems to remove the short name in favour of only longer names.

**Comment by phoe** [comment]
We might want to ask @quicklisp to try and make this estimate by trying to build the Quicklisp world with this nickname removed and getting a list of direct dependents that fail to build. This way, we can send out patches to all affected repositories that we become aware of this way.

**Comment by phoe** [comment]
> 19:51 < Xach> phoe: you could look at systems.txt and see who uses verbose. then change verbose, and try to load each of those things.

This sounds like a way forward. The current Quicklisp dist shows the following dependencies (and Verbose itself):

```bash
$ cat quicklisp/dists/quicklisp/systems.txt | grep verbose | cut -f 1 -d " "
cl-mpg123
cl-threadpool
colleen
flare
halftone
lichat-tcp-client
lichat-tcp-server
lichat-ws-server
lionchat
lispcord
maiden
trivial-swank
verbose
```

**Comment by Shinmera** [comment]
Does that cover transitive dependencies? Anyway, of those... all except cl-threadpool, lispcord, and trivial-swank are mine

**Comment by phoe** [comment]
Nope, just direct ones. My half-assed and maybe correct attempt and computing *all* dependents of Verbose:

```lisp
CL-USER> (let ((result (make-hash-table :test #'equal)))
           (labels ((recur (x)
                      (dolist (y (ql:who-depends-on x))
                        (unless (gethash y result)
                          (setf (gethash y result) t)
                          (recur y)))))
             (recur "verbose")
             (format t "~{~A~%~}"(alexandria:hash-table-keys result))))
trivial-swank
maiden-storage
maiden-serialize
maiden-relay
maiden-networking
maiden-twitter
maiden-lichat
maiden-irc
maiden-vote
maiden-trivia
maiden-throttle
maiden-talk
maiden-permissions
maiden-help
maiden-dictionary
maiden-core-manager
maiden-commands
maiden-chatlog
maiden-channel-relay
maiden-blocker
maiden-notify
maiden-medals
maiden-accounts
maiden-client-entities
maiden-lookup
maiden-weather
maiden-time
maiden-location
maiden-lastfm
maiden-crimes
maiden-api-access
maiden-urlinfo
maiden-silly
maiden-markov
maiden-emoticon
maiden-counter
maiden-activatable
maiden
example-bot
lispcord
lichat-ws-server
lichat-tcp-server
lionchat
lichat-tcp-client
halftone
flare-viewer
colleen
cl-threadpool-test
cl-mpg123-example
```

Please feel free to scold me and correct my code as appropriate.

**Comment by Shinmera** [comment]
Okey, I don't think I see anything new in there.

**Comment by Shinmera** [comment]
The band-aid has been ripped off.

**Comment by spreadLink** [comment]
Ouch.

But understandable. Good riddance to short nicknames, and thank you for your work.
