### ISSUE TITLE
Can't build a binary with trivial-dump-core because of the background thread

### ISSUE THREAD

**Issue by thiderman** [Shinmera/verbose#6]
So, I'm trying to build an executable of my project using [trivial-dump-core](https://github.com/rolpereira/trivial-dump-core). However, `save-lisp-and-die` cannot complete successfully since the `verbose-thread` is running in the background:

```
To load "chill":
  Load 1 ASDF system:
    chill
; Loading "chill"
..............
Switching to the BALLAND2006 optimizer
.......
Can't save image with more than one executing threadWhile evaluating the form starting at line 3, column 0
  of #P"/home/thiderman/common-lisp/chill/build/build.lisp":

debugger invoked on a SB-IMPL::SAVE-ERROR in thread
#<THREAD "main thread" RUNNING {1001A70103}>:
  Could not save core.
See also:
  The SBCL Manual, Node "Saving a Core Image"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY   ] Retry EVAL of current toplevel form.
  1: [CONTINUE] Ignore error and continue loading file "/home/thiderman/common-lisp/chill/build/build.lisp".
  2: [ABORT   ] Abort loading file "/home/thiderman/common-lisp/chill/build/build.lisp".
  3:            Ignore runtime option --load "build/build.lisp".
  4:            Skip rest of --eval and --load options.
  5:            Skip to toplevel READ/EVAL/PRINT loop.
  6: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

(SAVE-LISP-AND-DIE "chill" :TOPLEVEL #<FUNCTION CHILL:MAIN> :EXECUTABLE T :SAVE-RUNTIME-OPTIONS NIL :PURIFY #<unused argument> :ROOT-STRUCTURES NIL :ENVIRONMENT-NAME #<unused argument> :COMPRESSION NIL)
0] (bt:all-threads)

(#<SB-THREAD:THREAD "main thread" RUNNING {1001A70103}>
 #<SB-THREAD:THREAD "verbose-thread" RUNNING {1003975583}>)
0]
```

So, it can't save because of the `verbose-thread` running. I tried adding a call to `(setq v:*process-locally* t)` [early on in my source files](https://git.sr.ht/~thiderman/chill/tree/master/item/lisp/config.lisp#L3), but it seems that the thread has already started by the time that's executing. I'm pretty sure I need to tell `asdf` to do something somewhere before it loads `verbose`, but I really can't figure out what. For reference: [my .asd file](https://git.sr.ht/~thiderman/chill/tree/master/item/chill.asd)

I guess it's not an issue specific to this package, but I figured you would be able to help anyways. :sweat_smile:  Am I looking at the problem the right way, or am I doing something else wrong?

**Comment by Shinmera** [comment]
It mentions this problem in the documentation:

> When deploying an application the background thread might again cause problems as it is started by default and dumping an image with threads alive is not possible. Thus, you should call stop on *global-controller* before dumping and start after resuming the image. Alternatively you can push :verbose-no-init onto *features* before loading Verbose and then run start manually.

**Comment by thiderman** [comment]
And here I thought I read things through carefully. :woman_facepalming: 

Apologies for the noise.

**Comment by Shinmera** [comment]
No worries at all! We all miss stuff sometimes :)

If you use something like [Deploy](https://shinmera.github.io/deploy) instead you can achieve the desired behaviour through a hook, as illustrated here: https://github.com/Shirakumo/trial/blob/master/deploy.lisp#L21-L31

**Comment by thiderman** [comment]
Ooh, I'll take a look at that!
I'm a bit of a newbie and am just discovering things. `trivial-dump-core` was the first binary-producing thing that I was able to get to work. :sweat_smile: Since I've enjoyed using `verbose`, I'll probably go for `deploy` as well! Thanks again! :blush:

**Comment by Shinmera** [comment]
Sure, don't hesitate to ask if you have further issues!
